import type { Metadata } from "next";
import "../globals.css";
import {ThemeProvider} from "next-themes";
import StoreProvider from "@/app/StoreProvider";
import {Toaster} from "@/components/ui/toaster";
import {FooterComponent} from "@/components/customer/footer/FooterComponent";
import FooterOrganizer from "@/components/organizer/FooterOrganizer";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body className=" bg-khotixs-background-white dark:bg-khotixs-background-dark ">
        <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
        >


            <StoreProvider>
                {children}
            </StoreProvider>
            <FooterOrganizer />
            <Toaster />
        </ThemeProvider>
        </body>
        </html>
    );
}
