import type {Metadata} from "next";
import "../globals.css";
import {ThemeProvider} from "next-themes";
import {Toaster} from "@/components/ui/toaster";
import FooterOrganizer from "@/components/organizer/navbar/FooterOrganizer";
import NavbarOrganizerComponent from "@/components/organizer/navbar/NavbarOrganizerComponent";
import CategoriesOrganizerComponent from "@/components/organizer/navbar/categoriesOrganizerComponent";
import React from "react";
import {ApiProvider} from "@reduxjs/toolkit/query/react";
import StoreProvider from "@/app/StoreProvider";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body className=" bg-khotixs-background-white dark:bg-khotixs-background-dark ">
        <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
        >
            <StoreProvider>
                <NavbarOrganizerComponent/>
                <CategoriesOrganizerComponent/>
                {children}
                <FooterOrganizer/>
                <Toaster/>
            </StoreProvider>
        </ThemeProvider>
        </body>
        </html>
    );
}