export const eventData = [
    { month: 'Jan', value: 186 },
    { month: 'Feb', value: 305 },
    { month: 'Mar', value: 237 },
    { month: 'Apr', value: 73 },
    { month: 'May', value: 209 },
    { month: 'Jun', value: 214 },
    { month: 'Jun', value: 214 },
    { month: 'Jan', value: 186 },
    { month: 'Feb', value: 305 },
    { month: 'Mar', value: 237 },
    { month: 'Apr', value: 73 },
    { month: 'May', value: 209 },
    { month: 'Jun', value: 214 },
    { month: 'Jun', value: 214 },
];