// lib/data.ts

export const payments = [
    {
        id: "khotixs_#1",
        username: "Piseth",
        event: "The Rise Of The Queen",
        paymentMethod: "KHQR",
        paymentDate: "24-NOV-2024, 07:00AM",
        amount: 30.0,
    },
    {
        id: "khotixs_#2",
        username: "Seakngim",
        event: "The Rise Of The Queen",
        paymentMethod: "KHQR",
        paymentDate: "21-NOV-2024, 09:10AM",
        amount: 120.0,
    },
    {
        id: "khotixs_#3",
        username: "Sarandy",
        event: "The Rise Of The Queen",
        paymentMethod: "CREDIT & DEBIT CARD",
        paymentDate: "20-NOV-2024, 02:18PM",
        amount: 60.0,
    },
    {
        id: "khotixs_#4",
        username: "Soknem",
        event: "The Rise Of The Queen",
        paymentMethod: "KHQR",
        paymentDate: "20-NOV-2024, 04:06PM",
        amount: 120.0,
    },
    {
        id: "khotixs_#5",
        username: "Piseth",
        event: "The Rise Of The Queen",
        paymentMethod: "KHQR",
        paymentDate: "24-NOV-2024, 07:00AM",
        amount: 30.0,
    },
    {
        id: "khotixs_#6",
        username: "Seakngim",
        event: "The Rise Of The Queen",
        paymentMethod: "KHQR",
        paymentDate: "21-NOV-2024, 09:10AM",
        amount: 120.0,
    },
    {
        id: "khotixs_#7",
        username: "Sarandy",
        event: "The Rise Of The Queen",
        paymentMethod: "CREDIT & DEBIT CARD",
        paymentDate: "20-NOV-2024, 02:18PM",
        amount: 60.0,
    },
    {
        id: "khotixs_#8",
        username: "Soknem",
        event: "The Rise Of The Queen",
        paymentMethod: "KHQR",
        paymentDate: "20-NOV-2024, 04:06PM",
        amount: 120.0,
    },
]
