import type { Metadata } from "next";
import '../globals.css';
import NavbarComponent from "@/components/customer/NavbarComponent";
import { ThemeProvider } from "next-themes";
import { FooterComponent } from "@/components/customer/FooterComponent";
import { Toaster } from "@/components/ui/toaster"

export const metadata: Metadata = {
    title: "KHOTIXS",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className=" bg-khotixs-background-white ">
                <ThemeProvider
                    attribute="class"
                    defaultTheme="light"
                    enableSystem
                    disableTransitionOnChange
                >
                    <NavbarComponent />
                    {children}
                    <FooterComponent />
                    <Toaster />
                </ThemeProvider>
            </body>
        </html>
    );
}