import type { Metadata } from "next";
import '../globals.css';
import NavbarComponent from "@/components/ui/NavbarComponent";
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body className=" bg-khotixs-background-white ">
        <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
        >
            <NavbarComponent />
            {children}
        </ThemeProvider>
        </body>
        </html>
    );
}